// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6QjsKAkYpXh0emzxDBohax0lqTsDQrG0',
    appId: '1:866960631361:web:28a89bd987505de0f988c0',
    messagingSenderId: '866960631361',
    projectId: 'myproject-7e852',
    authDomain: 'myproject-7e852.firebaseapp.com',
    databaseURL: 'https://myproject-7e852-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-7e852.firebasestorage.app',
    measurementId: 'G-JVTQ796VHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzCNegXy1mE6PBuezRTa96lgex35OhHo',
    appId: '1:866960631361:android:4c1ffbef7bd289c2f988c0',
    messagingSenderId: '866960631361',
    projectId: 'myproject-7e852',
    databaseURL: 'https://myproject-7e852-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-7e852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzXg1TA8CBtRb4zT0tRuuFtJdw0AFRwxo',
    appId: '1:866960631361:ios:b811f44e8d485770f988c0',
    messagingSenderId: '866960631361',
    projectId: 'myproject-7e852',
    databaseURL: 'https://myproject-7e852-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-7e852.firebasestorage.app',
    androidClientId: '866960631361-v4nmi5ocbqa8num5o5ndihce3buuabtt.apps.googleusercontent.com',
    iosClientId: '866960631361-gqmjk7ioknfirrpr7ttb6ilr11qvc33i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bt1Quocnghia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzXg1TA8CBtRb4zT0tRuuFtJdw0AFRwxo',
    appId: '1:866960631361:ios:b811f44e8d485770f988c0',
    messagingSenderId: '866960631361',
    projectId: 'myproject-7e852',
    databaseURL: 'https://myproject-7e852-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-7e852.firebasestorage.app',
    androidClientId: '866960631361-v4nmi5ocbqa8num5o5ndihce3buuabtt.apps.googleusercontent.com',
    iosClientId: '866960631361-gqmjk7ioknfirrpr7ttb6ilr11qvc33i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bt1Quocnghia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6QjsKAkYpXh0emzxDBohax0lqTsDQrG0',
    appId: '1:866960631361:web:cf32e8fa032b5d21f988c0',
    messagingSenderId: '866960631361',
    projectId: 'myproject-7e852',
    authDomain: 'myproject-7e852.firebaseapp.com',
    databaseURL: 'https://myproject-7e852-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-7e852.firebasestorage.app',
    measurementId: 'G-X2B64LK4DG',
  );
}
